env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['plugin:@typescript-eslint/recommended', 'plugin:react/recommended', 'htmlacademy/es6']

rules:
  '@typescript-eslint/indent': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

